add sifive_uart
machineware-gmbh/vcml pull request #85
Opened 2024-02-06 13:17 UTC by RubBra

2024-02-06 15:08 UTC, janweinstock requested changes

2024-02-06 15:08 UTC, janweinstock commented on src/vcml/models/serial/sifive_uart.cpp
> +    update_tx();
why update tx during receiver control write?

2024-02-06 15:08 UTC, janweinstock commented on src/vcml/models/serial/sifive_uart.cpp
> +    update_tx();
`txctrl` should also handle setting number of stop bits (bit 1 in `txctrl`)

2024-02-06 15:08 UTC, janweinstock commented on src/vcml/models/serial/sifive_uart.cpp
> +    serial_tx.set_baud(SERIAL_115200BD);
serial_tx is missing some setup:
* setting data bits to 8
* setting parity to none

2024-02-06 15:53 UTC, RubBra commented on src/vcml/models/serial/sifive_uart.cpp
> +    return val;
on further inspection the enabled check doesn't seem to be necessary. disabling rx should only disable enqueuing not dequeuing

2024-02-07 13:36 UTC, janweinstock approved these changes

2024-02-07 13:47 UTC, merged